server:
  port: 8901
dubbo:
  scan:
    base-packages: com.cloud.dubbo.app.service
  registry:
    address: spring-cloud://127.0.0.1
  protocol:
    name: dubbo
    port: -1
spring:
  application:
    name: dubbo-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
