server:
  port: 8902
dubbo:
  registry:
    address: spring-cloud://127.0.0.1
  protocol:
    name: dubbo
    port: -1
  cloud:
    subscribed-services: dubbo-provider
spring:
  application:
    name: dubbo-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:mysql://localhost:3306/seata_consumer?allowMultiQueries=true&useSSL=false
    password: zhujing1016
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: true

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: ${spring.application.name}
  enable-auto-data-source-proxy: true
  config:
    type: nacos
    nacos:
      namespace:
      serverAddr: 127.0.0.1:8848
      group: SEATA_GROUP
      userName: "nacos"
      password: "nacos"
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      namespace:
      userName: "nacos"
      password: "nacos"

logging:
  level:
    io.seata: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'