server:
  port: 8902
dubbo:
  registry:
    address: spring-cloud://127.0.0.1
  protocol:
    name: dubbo
    port: -1
  cloud:
    subscribed-services: dubbo-provider
spring:
  application:
    name: dubbo-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
